---

- name: Add user
  user:
    name: "{{ item.name }}"
    shell: /bin/bash

- name: Add public key to authorized keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.key }}"  
  
